use serde::{Deserialize, Serialize};

/// Message-level mismatch details for UI display.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MismatchDetail {
    pub id: String,
    pub mismatch_type: String,
    pub source_uid: Option<String>,
    pub dest_uid: Option<String>,
    pub source_message_id: Option<String>,
    pub dest_message_id: Option<String>,
    pub source_size_bytes: Option<u64>,
    pub dest_size_bytes: Option<u64>,
    pub source_date: Option<String>,
    pub dest_date: Option<String>,
    pub subject: Option<String>,
    pub acceptance_status: Option<AcceptanceStatus>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AcceptanceStatus {
    pub operator: String,
    pub reason: String,
    pub accepted_at: String,
}

/// Verification summary with mismatch breakdown.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationDetail {
    pub job_id: String,
    pub total_source_messages: u64,
    pub total_dest_messages: u64,
    pub exact_matches: u64,
    pub missing_count: u64,
    pub extra_count: u64,
    pub changed_count: u64,
    pub mismatch_summary: MismatchSummary,
    pub sample_mismatches: Vec<MismatchDetail>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MismatchSummary {
    pub total_mismatches: u64,
    pub by_type: MismatchCounts,
    pub accepted: u64,
    pub pending_review: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MismatchCounts {
    pub exact_match: u64,
    pub content_match: u64,
    pub date_size_match: u64,
    pub message_id_only: u64,
    pub missing: u64,
    pub extra: u64,
    pub duplicated: u64,
    pub folder_mismatch: u64,
    pub changed: u64,
}

impl MismatchCounts {
    pub fn total(&self) -> u64 {
        self.exact_match
            + self.content_match
            + self.date_size_match
            + self.message_id_only
            + self.missing
            + self.extra
            + self.duplicated
            + self.folder_mismatch
            + self.changed
    }

    pub fn confidence_level(&self) -> String {
        if self.exact_match + self.content_match == 0 {
            return "low".to_string();
        }
        let exact_pct =
            (self.exact_match as f64 * 100.0) / (self.exact_match + self.content_match) as f64;
        if exact_pct >= 95.0 {
            "high".to_string()
        } else if exact_pct >= 80.0 {
            "medium".to_string()
        } else {
            "low".to_string()
        }
    }
}

/// Display-friendly description of each mismatch type.
pub fn mismatch_type_description(mismatch_type: &str) -> &'static str {
    match mismatch_type {
        "exact_match" => "Message-ID, content hash, and date all match (100% confidence)",
        "content_match" => "Content hash and date match, but Message-ID differs (99% confidence)",
        "date_size_match" => "Date and size match; detects renames (95% confidence)",
        "message_id_only" => {
            "Message-ID matches but size/date differs; may indicate corruption (80% confidence)"
        }
        "missing" => "Present in source, absent in destination",
        "extra" => "Present in destination, absent in source (may be post-migration addition)",
        "duplicated" => "Multiple instances of same message-ID in destination",
        "folder_mismatch" => "Same message appears in different folder on destination",
        "changed" => "Same UID but different size/content (indicates modification)",
        _ => "Unknown mismatch type",
    }
}

/// Operator-facing guidance for different mismatch types.
pub fn mismatch_remediation(mismatch_type: &str) -> &'static str {
    match mismatch_type {
        "exact_match" => "No action needed; message verified exactly.",
        "content_match" => {
            "Message content is correct; Message-ID may have been regenerated by provider."
        }
        "date_size_match" => "Message content appears correct despite Message-ID mismatch.",
        "message_id_only" => {
            "REVIEW: Message-ID matches but size/date differ; check if message was modified in transit."
        }
        "missing" => "ATTENTION: Review exclusion rules or retry final delta sync.",
        "extra" => {
            "REVIEW: Confirm this is a post-migration addition; accept exception if expected."
        }
        "duplicated" => {
            "ATTENTION: Destination has duplicate messages; investigate provider folder mapping."
        }
        "folder_mismatch" => {
            "ATTENTION: Message exists in different folder; verify folder mapping is correct."
        }
        "changed" => {
            "ATTENTION: Message content differs; possible corruption or provider modification."
        }
        _ => "ATTENTION: Unknown issue; review in detail.",
    }
}

/// Risk level for different mismatch types (for UI coloring/prioritization).
pub fn mismatch_severity(mismatch_type: &str) -> &'static str {
    match mismatch_type {
        "exact_match" => "ok",
        "content_match" => "ok",
        "date_size_match" => "ok",
        "message_id_only" => "warning",
        "missing" => "error",
        "extra" => "info",
        "duplicated" => "error",
        "folder_mismatch" => "error",
        "changed" => "error",
        _ => "warning",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mismatch_counts_total() {
        let counts = MismatchCounts {
            exact_match: 100,
            content_match: 10,
            date_size_match: 5,
            message_id_only: 2,
            missing: 1,
            extra: 0,
            duplicated: 0,
            folder_mismatch: 0,
            changed: 0,
        };
        assert_eq!(counts.total(), 118);
    }

    #[test]
    fn high_confidence_with_mostly_exact_matches() {
        let counts = MismatchCounts {
            exact_match: 950,
            content_match: 50,
            date_size_match: 0,
            message_id_only: 0,
            missing: 0,
            extra: 0,
            duplicated: 0,
            folder_mismatch: 0,
            changed: 0,
        };
        assert_eq!(counts.confidence_level(), "high");
    }

    #[test]
    fn medium_confidence_with_mixed_matches() {
        let counts = MismatchCounts {
            exact_match: 800,
            content_match: 200,
            date_size_match: 0,
            message_id_only: 0,
            missing: 0,
            extra: 0,
            duplicated: 0,
            folder_mismatch: 0,
            changed: 0,
        };
        assert_eq!(counts.confidence_level(), "medium");
    }

    #[test]
    fn missing_messages_are_errors() {
        assert_eq!(mismatch_severity("missing"), "error");
    }

    #[test]
    fn extra_messages_are_info() {
        assert_eq!(mismatch_severity("extra"), "info");
    }

    #[test]
    fn exact_matches_are_ok() {
        assert_eq!(mismatch_severity("exact_match"), "ok");
    }

    #[test]
    fn descriptions_exist_for_all_types() {
        for mismatch_type in &[
            "exact_match",
            "content_match",
            "date_size_match",
            "message_id_only",
            "missing",
            "extra",
            "duplicated",
            "folder_mismatch",
            "changed",
        ] {
            let desc = mismatch_type_description(mismatch_type);
            assert!(!desc.is_empty());
            assert!(!desc.contains("Unknown"));
        }
    }
}
